### ISSUE TITLE
The API is not responding with any data at api/gstin/ for get all GSTIN

### ISSUE THREAD

**Issue by Aashutosh-kr** [rohitpithisaria/frontendassignment#1]
The API is not responding with any data at api/gstin/  for get all GSTIN. It is always sending invalid token and when I used token from other requests, it sent no data, only a blank array of GSTIN.

![p2](https://user-images.githubusercontent.com/95764284/189059906-b0214d8c-88bd-4f7b-86a6-14528239018a.png)
![p1](https://user-images.githubusercontent.com/95764284/189059914-c54044fe-d95e-4bbc-9d99-4e9023ebf0ef.png)

**Comment by rohitpithisaria** [comment]
Hello,

Thanks for your reply.

I have removed the authentication now. Can you please try now and let me
know?

Thanks

Regards,
RP

**Comment by Aashutosh-kr** [comment]
The API is still sending a blank array of gstin for my email but is working
fine with the test user given.

**Comment by rohitpithisaria** [comment]
Can you please check now?

Regards,
RP

**Comment by Aashutosh-kr** [comment]
The api is now working with normal email types like name@anymail.com. Previously, I was using something between name and @ with a '+' sign. This is causing a problem.
I am closing the issue as it seems to work fine with normal email syntax but should also work with any email address.
